languageCode = "fr"
defaultContentLanguage = "fr"
#defaultContentLanguageInSubdir = true
title = "Pilot"
baseURL = "https://www.pilot.pm"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

enableMissingTranslationPlaceholders = true
summaryLength = 30
enableRobotsTXT = true

[imaging]
quality = 100

[build]
#Used by PurgeCSS
writeStats = true

[markup]
[markup.goldmark]
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true
    autoHeadingIDType = "github"
  [markup.goldmark.renderer]
    hardWraps = true
    unsafe = true
    xhtml = false

[params]
  appUrl = "https://app.pilot.pm"
  appName = "Pilot"
  appTwitter = "pilot_app"
  appEmail = "hello@pilot.pm"
  appSupportEmail = "support@pilot.pm"
  copyright = "Copyright 2020"
  image = "images/features/teamwork.png"
  brandColor = "gray"

[languages]
  [languages.en]
    LanguageName = "English"
    description = "Pilot helps teams that produce content."
    languageCode = "en"
    weight = 2

  [languages.fr]
    LanguageName = "Français"
    description = "Pilot aide les équipes qui produisent des contenus."
    languageCode = "fr"
    weight = 1
