[build]
publish = "public"
command = "hugo --gc"

[context.production.environment]
HUGO_VERSION = "0.79.0"
NODE_ENV = "production"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.79.0"
NODE_ENV = "production"

[context.branch-deploy]
command = "hugo --gc --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.79.0"
NODE_ENV = "production"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
NODE_ENV = "production"

# [[redirects]]
#   from = "/"
#   to = "/en"
#   status = 301
#   force = true
#   query = {path = ":path"}
#   conditions = {Language = ["en"]}
