languageCode = "en"
defaultContentLanguage = "en"
#defaultContentLanguageInSubdir = true
title = "Pilot"
baseURL = "https://pilot.pm"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
  # baseUrl = process.env.BASE_URL || 'http://localhost:1313'
  appUrl = "https://app.pilot.pm"
  appName = "Pilot"
  appTwitter = "pilot_app"
  appEmail = "hello@pilot.pm"
  appSupportEmail = "support@pilot.pm"
  descriptionShort = "The content production platform for marketing teams."
  description = "Organize all your content production in one place. All team access the last validated version of each document or file."
  copyright = "Copyright 2019"

[languages]
  [languages.en]
    LanguageName = "English"
    languageCode = "en"
    weight = 1
    contentDir = "content/en"
  [languages.fr]
    LanguageName = "Français"
    languageCode = "fr"
    weight = 2
    contentDir = "content/fr"