baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Pilot"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]


DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
copyright = "Everything is mine"

[languages]
[languages.en]
  LanguageName = "English"
  languageCode = "en"
  title = "Pilot"
  weight = 1
  contentDir = "content/en"
[languages.fr]
  LanguageName = "Français"
  languageCode = "fr"
  title = "Pilot"
  weight = 2
  contentDir = "content/fr"